version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.4.0
    working_directory: ~/makecancelable
    steps:
      - checkout
      - restore_cache:
          name: Restore node_modules cache
          keys:
            - v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-node-{{ arch }}-{{ .Branch }}-
            - v1-node-{{ arch }}-
      - run:
          name: Nodejs Version
          command: node --version
      - run:
          name: Install Packages
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Test
          command: npm test
      - save_cache:
          name: Save node_modules cache
          key: v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
